[book]
authors = ["The qaul developers"]
multilingual = false
src = "src"
title = "qaul developer manual"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "rust"
git-repository-url = "https://git.qaul.org/qaul/qaul/-/tree/develop/docs/developer"
git-repository-icon = "fa-git"
