[book]
authors = ["The irdest developers"]
multilingual = false
src = "src"
title = "irdest developer manual"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "rust"
git-repository-url = "https://git.irde.st/we/irdest/-/tree/develop/docs/developer"
git-repository-icon = "fa-git"
