stages:
  - test
  - build

build-rust:
  needs: []
  tags: [ qaul-nix ]
  stage: build
  script:
    - nix-build nix -A qaul-rust

build-web:
  needs: []
  tags: [ qaul-nix ]
  stage: build
  script:
    - nix-build nix -A qaul-web
  artifacts:
    paths:
      - result/*

build-website:
  needs: []
  tags: [ qaul-nix ]
  stage: build
  script:
    - nix-build nix -A qaul-website
  artifacts:
    paths:
      - result/*
