# Top level ci file that `triggers` the pipelines as per the structure defined

rust-components:
  stage: build
  trigger: 
    include: '**/*/rust-components-ci.yml'
    strategy: depend

android-components:
  stage: build
  trigger:
    include: 
    - '**/*/android-support-crate.yml'
    - '**/*/irdest-android-app.yml'
    strategy: depend

docs: 
  stage: build
  trigger:
    include: '**/*/docs-website-ci.yml'
    strategy: depend