[workspace]
members = [
    # The decentralised router
    "ratman",
    "ratman/client-lib",
    "ratman/identity",
    "ratman/netmod",
    "ratman/types",

    # Various utility crates
    "utils/clockctrl",
    "utils/task-notify",

    # Available netmod drivers
    "netmods/netmod-mem",
    "netmods/netmod-inet",
    "netmods/netmod-lan",
    "netmods/netmod-wd",

    # End-user applications
    "clients/irdest-echo",
    "clients/irdest-proxy",
]
