[workspace]
members = [
    # Encrypted & async database engine
    "utils/alexandria",
    "utils/alexandria-tags",

    # The decentralised router
    "ratman",
    "ratman/client-lib",
    "ratman/configure",
    "ratman/harness",
    "ratman/identity",
    "ratman/netmod",
    "ratman/types",

    # Various utility crates
    "utils/clockctrl",
    "utils/libopus-sys",
    "utils/opus-rs",
    "utils/permute",
    "utils/task-notify",
    "utils/visn",

    # Available netmod drivers
    "netmods/netmod-mem",
    "netmods/netmod-tcp",
    "netmods/netmod-udp",
    "netmods/netmod-wd",

    # End-user applications
    # "clients/hubd",
    # "clients/irdest-gtk",
    # "utils/android-support",
    # "utils/android-tracing"
]
