[workspace]
members = [
    # Encrypted & async database engine
    "utils/alexandria",
    "utils/alexandria-api",
    "utils/alexandria-tags",

    # Main qaul identity & storage library
    "irdest-core",
    "irdest-core/types",

    # RPC core utilities
    "rpc-core/irpc-sdk",
    "rpc-core/irpc-broker",

    # qaul developer SDKs
    "sdk/irdest-sdk",

    # The decentralised router
    "ratman",
    "ratman/harness",
    "ratman/identity",
    "ratman/netmod",
    "ratman/configure",

    # Various utility crates
    "utils/task-notify",
    "utils/clockctrl",
    "utils/libopus-sys",
    "utils/opus-rs",
    "utils/permute",
    "utils/visn",

    # Available netmod drivers
    "netmods/netmod-mem",
    "netmods/netmod-tcp",
    "netmods/netmod-udp",
    "netmods/netmod-wd",

    # Set of services in qaul
    "services/ping",

    # End-user applications
    "clients/hubd",
    "clients/irpc-client",
    "clients/irdest-gtk",
]
