# SPDX-FileCopyrightText: 2022 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later WITH LicenseRef-AppStore

[package]
name = "clockctrl"
description = "An asynchronous framework to provide various clock stepping for reactors"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
async-std = { version = "1.0", features = ["unstable"] }