[book]
authors = ["The qaul developers"]
language = "en"
multilingual = false
src = "src"
title = "qaul user manual"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "rust"
git-repository-url = "https://git.qaul.org/qaul/qaul/-/tree/develop/docs/user"
git-repository-icon = "fa-git"
