[package]
name = "libirdestdroid"
description = "An irdest-core and ratman shim for Android"
version = "0.1.0"
license = "APGL-3.0-or-later"
authors = ["Katharina Fey <kookie@spacekookie.de>", "Leonora Tindall <nora@nora.codes>"]
edition = "2018"

[lib]
name = "irdestdroid"
crate-type = ["cdylib"]

[dependencies]
async-std = "1.0"
bincode = "1.0"
jni = { version = "0.14", default-features = false }
log = "*"
tempfile = "3.0"
tracing = { version = "0.1" }
libc = "0.2"

irdest-core = { path = "../../irdest-core", features = ["ffi-java"] }
netmod-wd = { path = "../../netmods/netmod-wd" }
netmod-tcp = { path = "../../netmods/netmod-tcp" }        
ratman = { path = "../../ratman" }
ratman-configure = { path = "../../ratman/configure", features = ["android"] }
ratman-netmod = { path = "../../ratman/netmod" }



[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.8"
android-tracing = { path = "../android-tracing" }
