baseURL = "/"
title = "qaul – قول"
theme = "qaul-theme"
DefaultContentLanguage = "en"

[params]
  description = "Internet independent wireless mesh communication app"

[languages]
  [languages.en]
    weight = 1
    LanguageName = "English"
  [languages.de]
    weight = 3
    LanguageName = "Deutsch"
  [languages.ar]
    weight = 2
    LanguageName = "العربية"

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
