# Script that runs in `irdest-android-app` pipeline after it has been created
stages:
  - build
  - test
  - artifacts

# Our ultimately orz docker image
image: irdest/android-build-env

# Move to android dir before running CI on it
before_script:
  - cd clients/android

# Run Lint
Run Lint:
   interruptible: true
   stage: build
   script:
     - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
   artifacts:
     when: always
     paths:
       - "**/reports/*"
     expire_in: 45 mins

# Make Project
Build Application & Generate APK:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - "**/apk/*"
    expire_in: 45 mins

# Run all tests, if any fails, interrupt the pipeline(fail it)
Run Unit Tests:
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

Upload Artifacts:
  stage: artifacts
  when: always
  script:
    - mv app/build/outputs/apk/debug/app-debug.apk ../../irdest-debug.apk
    - mv app/lint/reports/ ../../ && cd $_
  artifacts:
    when: always
    paths:
      - irdest-debug.apk
      - reports
