[package]
name = "opus-rs"
version = "0.4.0"
authors = ["The qaul.net deveolpers <contact@qaul.net>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
description = "Safe Rust bindings for libopus"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["opus", "codec", "voice", "sound", "audio"]
categories = ["api-bindings", "encoding", "compression",
	"multimedia::audio", "multimedia::encoding"]

repository = "https://git.open-communication.net/qaul/opus-rs"

[dependencies]
libopus-sys = { path = "../libopus-sys" }
libc = "0.2"
