[package]
name = "alexandria"
description = "An encrypted document-oriented database with tag based query support"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
repository = "https://git.irde.st/we/irdest"
documentation = "https://docs.rs/alexandria"
license = "GPL-3.0-or-later"
edition = "2018"
build = "build.rs"

[dependencies]
id = { version ="0.6.0", path = "../../ratman/identity", features = ["digest", "random", "aligned"], package = "ratman-identity" }
alexandria-tags = { version = "0.2", path = "../alexandria-tags" }

async-std = { version = "1.0", features = ["unstable", "attributes"] }
async-trait = "0.1"
atomptr = "1.0"
bincode = "1.0"
byteorder = "1.0"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
keybob = "0.4"
protobuf = "2.19"
rand = "0.7"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
sodiumoxide = "0.2.5"
thiserror = "1.0"
toml = "0.5"
tracing = "0.1"

[build-dependencies]
protoc-rust = "2.19"

[dev-dependencies]
bincode = "1.0"
ed25519-dalek = "1.0.0-pre.3"
tempfile = "3.0"
tracing-subscriber = { version = "0.2", features = ["fmt"] }