[book]
authors = ["Jess 3Jane", "qaul Community"]
multilingual = false
src = "src"
title = "HTTP API Documentation"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://git.qaul.org/qaul/qaul/-/tree/develop/docs%2Fhttp-api"
git-repository-icon = "fa-git"
