[package]
name = "ratman-types"
description = "Encoding types for the Ratman API"
version = "0.4.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-std = "1.0"
byteorder = "1.0"
protobuf = "2.19"
chrono = { version = "0.4", features = ["serde"] }
ratman-identity = { version ="0.6", path = "../identity", features = ["random"] }
thiserror = "1.0"
regex = "1"

serde_json = { version = "1.0", optional = true }

[build-dependencies]
protoc-rust = "2.19"
