[package]
name = "irdest-echo"
version = "0.1.0"
edition = "2018"

[dependencies]
ratman-client = { version = "0.1", path = "../../ratman/client-lib/" }
async-std = { version = "1.0", features = ["attributes"] }