[package]
name = "ratman-client"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
async-std = "1.0"
types = { path = "../types", version = "0.1.0", package = "ratman-types" }
thiserror = "1.0"