[package]
name = "libopus-sys"
version = "0.4.0"
authors = ["The qaul developers <contact@qaul.org>", "Katharina Fey <kookie@spacekookie.de"]
description = "Rust bindings to libopus"
keywords = ["opus"]
readme = "README.md"
repository = "https://git.qaul.org/qaul/qaul"
license = "Apache-2.0"

[dependencies]

[build-dependencies]
cmake = "0.1"
bindgen = { version = "0.54", optional = true }

[features]
# Used internally to generate lib.rs
build-bindgen = ["bindgen"]
