[package]
name = "irdest-sdk"
description = "Client SDK for libqaul"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
ircore-types = { version = "0.1", path = "../../irdest-core/types" }
irpc-sdk = { version = "0.1", path = "../../rpc-core/irpc-sdk" }
