[package]
name = "ratman"
description = "A delay tolerant, journaled, and distributed userspace packet router"
license = "AGPL-3.0"
version = "0.3.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

# Stand-alone ratman daemon binary
[[bin]]
name = "ratmand"
required-features = ["daemon"]

# A client tool to connect to the ratman daemon
[[bin]]
name = "ratcat"
required-features = ["ratcat"]

[features]
default = []
tcp = ["netmod-tcp"]
udp = ["netmod-udp"]
daemon = ["cli", "tcp", "udp"]
ratcat = ["cli", "directories", "serde_json", "ratman-client"]
cli = ["types", "clap", "tracing-subscriber", "nix"]

[dependencies]
async-std = { version = "1.0", features = ["std", "unstable"] }
bincode = "1.0"
byteorder = "1.0"
chrono = { version = "0.4", features = ["serde"] }
protobuf = "2.19"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
tracing-futures = "0.2"
twox-hash = "1.5"

# Sub-components
clockctrl = { version = "0.1", path = "../utils/clockctrl" }
identity = { version ="0.6", path = "identity", package = "ratman-identity", features = ["digest", "random"] }
netmod = { version ="0.5.0", path = "netmod", package = "ratman-netmod"}
task-notify = { version = "0.1", path = "../utils/task-notify" }

# Dependencies required for various binary targets
types = { version = "0.1", path = "types", package = "ratman-types", optional = true }
clap = { version = "2.0", optional = true, features = ["wrap_help", "color", "suggestions"] }
tracing-subscriber = { version = "0.2", optional = true, features = ["fmt"] }
directories = { version = "4.0.1", optional = true }
serde_json = { version = "1.0", optional = true }
ratman-client = { version = "0.1", path = "client-lib", optional = true }
nix = { version = "0.23", optional = true }

# Bundled network modules are all optional dependencies
netmod-tcp = { path = "../netmods/netmod-tcp", version = "0.4", optional = true }
netmod-udp = { path = "../netmods/netmod-udp", version = "0.2", optional = true }

[dev-dependencies]
netmod-mem = { path = "../netmods/netmod-mem", version = "0.4" }
bincode = "1.2"
