[package]
name = "irdest-ping"
description = "A test service, demonstrating how to use irdest-core, and the irpc-sdk"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
irpc-sdk = { path = "../../rpc-core/irpc-sdk", version = "0.1" }
irdest-sdk = { path = "../../sdk/irdest-sdk" }

async-std = { version = "1.0", features = ["attributes"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "env-filter"] }
