[package]
name = "irdest-chat"
description = "irdest chat service"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
irdest-sdk = { path = "../../sdk/irdest-sdk" }
