[package]
name = "webui"
description = "A service to host and serve a cross-platform web UI"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
tide = "*"