[package]
name = "irdest-webui"
description = "A service to host and serve a cross-platform web UI"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
tide = "0.16"
irpc-sdk = { path = "../../rpc-core/irpc-sdk" }
irdest-sdk = { path = "../../sdk/irdest-sdk" }
tracing = "0.1"

[dev-dependencies]
irdest-core = { path = "../../irdest-core" }
irpc-broker = { path = "../../rpc-core/irpc-broker" }
ratman-harness = { path = "../../ratman/harness" }
async-std = { version = "1.0", features = ["attributes"] }
tracing-subscriber = { version = "0.2", features = ["fmt"] }