[book]
authors = ["Katharina Fey", "Mathias Jud", "Jess 3Jane"]
multilingual = false
src = "src"
title = "qaul Contributors Manual"

[build]
create-missing = false

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://git.qaul.org/qaul/qaul/-/tree/develop/docs%2Fcontributors"
git-repository-icon = "fa-git"
